root: true
parser: babel-eslint
extends: airbnb/base
rules:
  brace-style: [2, stroustrup, {allowSingleLine: false}]
  no-console: 0
  prefer-template: 0
  func-names: 0
  prefer-rest-params: 0
  no-lone-blocks: 0
  no-use-before-define: 0
  quotes: 0
  max-len: 0
  no-param-reassign: 0
