# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

version: "{build}"

clone_depth: 10

environment:
  matrix:
    - nodejs_version: "5"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  - 'git config --global user.email "you@example.com" && git config --global user.name "Your Name"'
  - node --version && npm --version
  - npm test

matrix:
  fast_finish: true

cache:
  - 'node_modules -> package.json'              # local npm modules
